name: gitleaks

on:
  push:
  pull_request:

jobs:
  scan:
    name: scan for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: docker://zricethezav/gitleaks:v8.24.3
        with:
          args: detect --source=. --redact -v --exit-code=2 --report-format=sarif --report-path=results.sarif
